# all: test vet staticcheck

# test:
# 	go test -v ./...

# vet:
# 	go vet ./...

# staticcheck:
# 	staticcheck ./...

get-pkgs:
	go get -d ./...

build:
	go build -o ./bin/ ./...

run:
	go run ./cmd/main.go

migrate:
	go run ./cmd/migration/migration.go